swagger: '2.0'
info:
  version: 0.0.0
  title: Swagger petstore
  description: swagger demonstration

host: localhost:9001
paths:
  /pets:
    get:
      description: Returns all pets
      operationId: findPets
      produces:
      - application/json
      responses:
        default:
          description: Return the matching pets
          schema:
            type: array
            items:
              $ref: '#/definitions/pet'
    post:
      description: Creates a new pet in store
      operationId: addPet
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - name: pet
          in: body
          description: The pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/pet'
      responses:
        201:
          description: Returns the newly-added pet
          schema:
            $ref: '#/definitions/pet'

definitions:
  pet:
    type: object
    required:
      - name
      - type
    properties:
      name:
        type: string
        minLength: 4
        maxLength: 6
      dob:
        type: string
        format: 'date'
      type:
        type: string
        enum: [cat, dog, bird, snake, duck]
